### PR TITLE
Add chosen options

### PR DESCRIPTION
**Pull request by alse**

### CODE REVIEW

**Comment by anand-clarion** [comment]
@alse could you add the test case for same

**Comment by arvindvyas** [comment]
@alse could you add the test case for same

**Comment by alse** [comment]
@arvindvyas I only touched the js, and I didn't see any js test suite in the project. 

Could you re-run the travis specs? It looks like a bundler problem.

**Comment by arvindvyas** [comment]
@alse tnx I will look into it once I will reach to my work again

**Comment by arvindvyas** [comment]
@alse  thanks

**Pull request merged**
